base_model: meta-llama/Meta-Llama-3-8B
model_type: LlamaForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: true
load_in_4bit: false
strict: false

chat_template: chatml
default_system_message: You are a creative and hilarious comedy writer that loves to craft jokes.

datasets:
  - path: /workspace/data/haha-v1.jsonl
    type:
      system_prompt: "system\nYou are a creative and hilarious comedy writer that loves to craft jokes.<|im_end|>\n"
      field_system: system
      field_instruction: instruction
      field_output: output
      format: "<|im_start|>user\n{instruction}<|im_end|>\n<|im_start|>assistant\n"
      no_input_format: "<|im_start|>user\n{instruction}<|im_end|>\n<|im_start|>assistant\n"

dataset_prepared_path: last_run_prepared
val_set_size: 0.01
output_dir: /workspace/output

adapter: lora
lora_model_dir:

sequence_len: 64
sample_packing: true
pad_to_sequence_len: true
eval_sample_packing: false

lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:
lora_modules_to_save:
  - embed_tokens
  - lm_head

wandb_project: haha
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

max_steps:
gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 4
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0001
save_safetensors: true

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true
s2_attention:

warmup_steps: 10
evals_per_epoch: 4
eval_table_size:
eval_max_new_tokens: 128
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0

special_tokens:
  bos_token: "<|im_start|>"
  eos_token: "<|im_end|>"
  unk_token: "<unk>"
  pad_token: <|end_of_text|>
tokens:
  - "<|im_start|>"
